"""add user id in extractions

Revision ID: 7d77479bc79f
Revises: 17dcc111ddce
Create Date: 2026-08-04 10:51:25.338935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d77479bc79f'
down_revision: Union[str, Sequence[str], None] = '17dcc111ddce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_extractions_user_id'), 'extractions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'extractions', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extractions', type_='foreignkey')
    op.drop_index(op.f('ix_extractions_user_id'), table_name='extractions')
    op.drop_column('extractions', 'user_id')
    # ### end Alembic commands ###
