"""add pgvector extension and embedding columns

Revision ID: c88c6c4a3fc0
Revises: 898dfb3a9ed2
Create Date: 2026-07-01 11:53:49.433094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'c88c6c4a3fc0'
down_revision: Union[str, Sequence[str], None] = '898dfb3a9ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: pgvector extension must be installed on PostgreSQL server first:
    # CREATE EXTENSION vector;
    op.add_column('entry', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('extractions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('monthlysummary', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('weeklysummary', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weeklysummary', 'embedding')
    op.drop_column('monthlysummary', 'embedding')
    op.drop_column('extractions', 'embedding')
    op.drop_column('entry', 'embedding')
    # ### end Alembic commands ###
